"""
Notifications API — alerts for low stock, DSS results, price changes.
Auto-generated by DSS runs and inventory events.
"""

from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from sqlalchemy import func

from app.database import get_db
from app.models import Notification, NotificationType, Product
from app.schemas import NotificationResponse, NotificationListResponse

router = APIRouter(prefix="/notifications", tags=["Notifications"])


def create_notification(
    db: Session,
    type: NotificationType,
    title: str,
    message: str = None,
    product_id: int = None,
    dss_report_id: int = None,
):
    """Helper — used by other modules to create notifications."""
    notif = Notification(
        type=type,
        title=title,
        message=message,
        product_id=product_id,
        dss_report_id=dss_report_id,
    )
    db.add(notif)
    db.flush()
    return notif


@router.get("", response_model=NotificationListResponse)
def list_notifications(
    unread_only: bool = False,
    limit: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
):
    query = db.query(Notification)
    if unread_only:
        query = query.filter(Notification.is_read == False)

    total_count = query.count()

    total_unread = (
        db.query(func.count(Notification.id))
        .filter(Notification.is_read == False)
        .scalar()
    ) or 0

    notifs = (
        query.order_by(Notification.created_at.desc())
        .limit(limit)
        .all()
    )

    items = []
    for n in notifs:
        product_name = None
        if n.product_id:
            product_name = db.query(Product.name).filter(Product.id == n.product_id).scalar()
        items.append(NotificationResponse(
            id=n.id,
            type=n.type.value,
            title=n.title,
            message=n.message,
            product_id=n.product_id,
            product_name=product_name,
            dss_report_id=n.dss_report_id,
            is_read=n.is_read,
            is_actioned=n.is_actioned,
            created_at=n.created_at,
        ))

    return NotificationListResponse(items=items, total=total_count, unread_count=total_unread)


@router.put("/{notification_id}/read")
def mark_read(notification_id: int, db: Session = Depends(get_db)):
    notif = db.query(Notification).filter(Notification.id == notification_id).first()
    if not notif:
        raise HTTPException(status_code=404, detail="Notification not found")
    notif.is_read = True
    db.commit()
    return {"success": True}


@router.put("/read-all")
def mark_all_read(db: Session = Depends(get_db)):
    db.query(Notification).filter(Notification.is_read == False).update({"is_read": True})
    db.commit()
    return {"success": True}


@router.delete("/{notification_id}")
def dismiss_notification(notification_id: int, db: Session = Depends(get_db)):
    notif = db.query(Notification).filter(Notification.id == notification_id).first()
    if not notif:
        raise HTTPException(status_code=404, detail="Notification not found")
    notif.is_actioned = True
    notif.is_read = True
    db.commit()
    return {"success": True}
