"""add forecast_cache table

Revision ID: 4495b1371412
Revises: f88fedcbeaa2
Create Date: 2026-04-19 17:22:46.509533
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '4495b1371412'
down_revision: Union[str, None] = 'f88fedcbeaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('yhat', sa.Float(), nullable=False),
    sa.Column('yhat_lower', sa.Float(), nullable=False),
    sa.Column('yhat_upper', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fc_product_date', 'forecast_cache', ['product_id', 'forecast_date'], unique=False)
    op.create_index('idx_fc_product_version', 'forecast_cache', ['product_id', 'model_version'], unique=False)
    op.create_index(op.f('ix_forecast_cache_forecast_date'), 'forecast_cache', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_cache_product_id'), 'forecast_cache', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_cache_product_id'), table_name='forecast_cache')
    op.drop_index(op.f('ix_forecast_cache_forecast_date'), table_name='forecast_cache')
    op.drop_index('idx_fc_product_version', table_name='forecast_cache')
    op.drop_index('idx_fc_product_date', table_name='forecast_cache')
    op.drop_table('forecast_cache')
    # ### end Alembic commands ###
