"""inventory_txn_subtypes

Revision ID: f88fedcbeaa2
Revises: 001_inventory_txn_subtypes
Create Date: 2026-04-06 13:26:50.579475
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f88fedcbeaa2'
down_revision: Union[str, None] = '001_inventory_txn_subtypes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
